[[spglib]]
arch = "aarch64"
git-tree-sha1 = "855adc5f6873d7edbf3dd1cef60dd90b04db6009"
os = "macos"

    [[spglib.download]]
    sha256 = "19a7f0c3f5b84c3525d537c815b8a7c4f7e026f87528e6ee24649840e800c7da"
    url = "https://github.com/JuliaBinaryWrappers/spglib_jll.jl/releases/download/spglib-v2.6.0+0/spglib.v2.6.0.aarch64-apple-darwin.tar.gz"
[[spglib]]
arch = "aarch64"
git-tree-sha1 = "26d04b0c52d25b7f04c49627846ed437fb9739e9"
libc = "glibc"
os = "linux"

    [[spglib.download]]
    sha256 = "065ad7e5acb40c2c19725791f85e55a1ea3e1cffed3b36640414a234d5638ba8"
    url = "https://github.com/JuliaBinaryWrappers/spglib_jll.jl/releases/download/spglib-v2.6.0+0/spglib.v2.6.0.aarch64-linux-gnu.tar.gz"
[[spglib]]
arch = "aarch64"
git-tree-sha1 = "c946fec2c8d9b49a46c40f4619757ffc3331aaad"
libc = "musl"
os = "linux"

    [[spglib.download]]
    sha256 = "1b4d70d9aa1faf44204798a2f08832eb89b8000e4037474ce95ec87e42aef135"
    url = "https://github.com/JuliaBinaryWrappers/spglib_jll.jl/releases/download/spglib-v2.6.0+0/spglib.v2.6.0.aarch64-linux-musl.tar.gz"
[[spglib]]
arch = "aarch64"
git-tree-sha1 = "df5669340a2876725f3fe0124a450c6f06e771a1"
os = "freebsd"

    [[spglib.download]]
    sha256 = "7fdb97ce8537362d70e897ff9ffbcb9c87f2290d530792e9c28888c580f08b18"
    url = "https://github.com/JuliaBinaryWrappers/spglib_jll.jl/releases/download/spglib-v2.6.0+0/spglib.v2.6.0.aarch64-unknown-freebsd.tar.gz"
[[spglib]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "c3416a33a252f8195b642402a6d635cdaed6f6ea"
libc = "glibc"
os = "linux"

    [[spglib.download]]
    sha256 = "e4cc25d865443dd256e7c0c05aeb76400707e1b8260970d1b654ca6827d8e520"
    url = "https://github.com/JuliaBinaryWrappers/spglib_jll.jl/releases/download/spglib-v2.6.0+0/spglib.v2.6.0.armv6l-linux-gnueabihf.tar.gz"
[[spglib]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "b2388fb83c6de5361a5fa9e30f25d37446784fe3"
libc = "musl"
os = "linux"

    [[spglib.download]]
    sha256 = "5385b98a615ed072020ee369c79b17b073d7da1befec235987ab9e72d5e5a718"
    url = "https://github.com/JuliaBinaryWrappers/spglib_jll.jl/releases/download/spglib-v2.6.0+0/spglib.v2.6.0.armv6l-linux-musleabihf.tar.gz"
[[spglib]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "88618c11ba941c84fccb45c011db84d8595eca6d"
libc = "glibc"
os = "linux"

    [[spglib.download]]
    sha256 = "f458146fad288ea240ec6fb8ba5074540cb4b737025a14b8c1b3153448559ea0"
    url = "https://github.com/JuliaBinaryWrappers/spglib_jll.jl/releases/download/spglib-v2.6.0+0/spglib.v2.6.0.armv7l-linux-gnueabihf.tar.gz"
[[spglib]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "fba452622b80e754fa570d369db03ca82003b6f5"
libc = "musl"
os = "linux"

    [[spglib.download]]
    sha256 = "4565a91cf377618ff8a852f2cb30156f6d5cd17cfefb31a1cefa7b4ddc4edbc8"
    url = "https://github.com/JuliaBinaryWrappers/spglib_jll.jl/releases/download/spglib-v2.6.0+0/spglib.v2.6.0.armv7l-linux-musleabihf.tar.gz"
[[spglib]]
arch = "i686"
git-tree-sha1 = "312a4142bdd5bc755e53c63f0750a2e3224cb004"
libc = "glibc"
os = "linux"

    [[spglib.download]]
    sha256 = "75eca53c28bf19f211f29d7439d996b7817debe5e872973a5f83a2ddedae588c"
    url = "https://github.com/JuliaBinaryWrappers/spglib_jll.jl/releases/download/spglib-v2.6.0+0/spglib.v2.6.0.i686-linux-gnu.tar.gz"
[[spglib]]
arch = "i686"
git-tree-sha1 = "bd25f9c3984608eaccb6425c1b8d7b05e1d79322"
libc = "musl"
os = "linux"

    [[spglib.download]]
    sha256 = "668b2f90fde7274ee4a0b364eb5987baee7aea5ecb024bbf70ba7f2e57cd978f"
    url = "https://github.com/JuliaBinaryWrappers/spglib_jll.jl/releases/download/spglib-v2.6.0+0/spglib.v2.6.0.i686-linux-musl.tar.gz"
[[spglib]]
arch = "i686"
git-tree-sha1 = "328af07a4ae7eac35d2d94be5490ff8eb165fa31"
os = "windows"

    [[spglib.download]]
    sha256 = "178b669414f0509b71094fb5e7fd6be8eb32474623f145c577a77a01a7f3e464"
    url = "https://github.com/JuliaBinaryWrappers/spglib_jll.jl/releases/download/spglib-v2.6.0+0/spglib.v2.6.0.i686-w64-mingw32.tar.gz"
[[spglib]]
arch = "powerpc64le"
git-tree-sha1 = "b77c6748d8c8fc56e3068e79b5419c23ef91985b"
libc = "glibc"
os = "linux"

    [[spglib.download]]
    sha256 = "56dd9dbd183a7326e2231083b0ff8b14fd39fef6b345a1f4f3a969ab8c30439d"
    url = "https://github.com/JuliaBinaryWrappers/spglib_jll.jl/releases/download/spglib-v2.6.0+0/spglib.v2.6.0.powerpc64le-linux-gnu.tar.gz"
[[spglib]]
arch = "riscv64"
git-tree-sha1 = "9a404fb94499c38831b64f602b20acd40ff4c55a"
libc = "glibc"
os = "linux"

    [[spglib.download]]
    sha256 = "d6be3217e669bdf8ec86e24772fa6ccd5a1651663f561e66654b1a7c4686ff29"
    url = "https://github.com/JuliaBinaryWrappers/spglib_jll.jl/releases/download/spglib-v2.6.0+0/spglib.v2.6.0.riscv64-linux-gnu.tar.gz"
[[spglib]]
arch = "x86_64"
git-tree-sha1 = "5470a7c4eba6274c2adfe49e63d27ff7630d2cbf"
os = "macos"

    [[spglib.download]]
    sha256 = "38f9e84ca08adaa22a0304904bcc4ca3a5ea992dd2a5fc96e86dc546364a2123"
    url = "https://github.com/JuliaBinaryWrappers/spglib_jll.jl/releases/download/spglib-v2.6.0+0/spglib.v2.6.0.x86_64-apple-darwin.tar.gz"
[[spglib]]
arch = "x86_64"
git-tree-sha1 = "594080b0a2332a5518b745ac6805394ab60a9888"
libc = "glibc"
os = "linux"

    [[spglib.download]]
    sha256 = "4f308fa778a9c046f32bf56e544e40df5f57ea2e71a1fe64c8189d278ae1a4d5"
    url = "https://github.com/JuliaBinaryWrappers/spglib_jll.jl/releases/download/spglib-v2.6.0+0/spglib.v2.6.0.x86_64-linux-gnu.tar.gz"
[[spglib]]
arch = "x86_64"
git-tree-sha1 = "1acc9b646d6ffc5ffbe0f890ddd4c1b0144b1ac1"
libc = "musl"
os = "linux"

    [[spglib.download]]
    sha256 = "b92d5f71ec5bbe048f378efa9bca3b85c1386fefa94ffc5ace485c29f45259f6"
    url = "https://github.com/JuliaBinaryWrappers/spglib_jll.jl/releases/download/spglib-v2.6.0+0/spglib.v2.6.0.x86_64-linux-musl.tar.gz"
[[spglib]]
arch = "x86_64"
git-tree-sha1 = "8517cb4ebd375618ff87385fba04af9cd0ad7eb4"
os = "freebsd"

    [[spglib.download]]
    sha256 = "a00345bb2d216dcbf097463248fa04181c92f8a869e8a55a2f0a26141036a6ba"
    url = "https://github.com/JuliaBinaryWrappers/spglib_jll.jl/releases/download/spglib-v2.6.0+0/spglib.v2.6.0.x86_64-unknown-freebsd.tar.gz"
[[spglib]]
arch = "x86_64"
git-tree-sha1 = "ed0daadf965f9c0b798d4b738187a265ca46374f"
os = "windows"

    [[spglib.download]]
    sha256 = "f89919df9393decda5495ef455c8d6a23a470127a94d5b6eec07d248b7239236"
    url = "https://github.com/JuliaBinaryWrappers/spglib_jll.jl/releases/download/spglib-v2.6.0+0/spglib.v2.6.0.x86_64-w64-mingw32.tar.gz"
