[[spglib]]
arch = "aarch64"
git-tree-sha1 = "70589bd2204d375b06f86eb2043d7bdfe76ee393"
os = "macos"

    [[spglib.download]]
    sha256 = "7be2f18c7edb63a86139be6e1a3999c39c0a1dfbe8d260d947b2b1ffa28de4ff"
    url = "https://github.com/JuliaBinaryWrappers/spglib_jll.jl/releases/download/spglib-v2.5.0+0/spglib.v2.5.0.aarch64-apple-darwin.tar.gz"
[[spglib]]
arch = "aarch64"
git-tree-sha1 = "0be64f5f1344ed4fe9f4c47449e3bbedae6dc0cc"
libc = "glibc"
os = "linux"

    [[spglib.download]]
    sha256 = "5cae52b06b76dba16b8989917eb534832c07c87aa04dfca0f0b9574d4dd20dbf"
    url = "https://github.com/JuliaBinaryWrappers/spglib_jll.jl/releases/download/spglib-v2.5.0+0/spglib.v2.5.0.aarch64-linux-gnu.tar.gz"
[[spglib]]
arch = "aarch64"
git-tree-sha1 = "dfca74d264f11a4f1e45ed07603c6c0141972c1c"
libc = "musl"
os = "linux"

    [[spglib.download]]
    sha256 = "cd2b6a28c6e84b0f99435a2cb54b8b36e57ba89a3c40bd91b2fb4e3b95cfb7e2"
    url = "https://github.com/JuliaBinaryWrappers/spglib_jll.jl/releases/download/spglib-v2.5.0+0/spglib.v2.5.0.aarch64-linux-musl.tar.gz"
[[spglib]]
arch = "aarch64"
git-tree-sha1 = "b4732840e410bffd0a74ad347753cf1fe58d340a"
os = "freebsd"

    [[spglib.download]]
    sha256 = "4b0bdfe7047238f902401676fb9d04859409fc74b723926056f909025d21d7dc"
    url = "https://github.com/JuliaBinaryWrappers/spglib_jll.jl/releases/download/spglib-v2.5.0+0/spglib.v2.5.0.aarch64-unknown-freebsd.tar.gz"
[[spglib]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "3a8637798bb8b700d1a620791dd428d79e7ef931"
libc = "glibc"
os = "linux"

    [[spglib.download]]
    sha256 = "fbea40c86b1a9d0ff04321930fca1539375c2f449c1b6634fd03fb157f61ea00"
    url = "https://github.com/JuliaBinaryWrappers/spglib_jll.jl/releases/download/spglib-v2.5.0+0/spglib.v2.5.0.armv6l-linux-gnueabihf.tar.gz"
[[spglib]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "3265ba1266a69ba7cef441f4ef1321ac71c06610"
libc = "musl"
os = "linux"

    [[spglib.download]]
    sha256 = "b3c0ad925832681ad2260ba1ffccc897f7253d8a3d264a8ea874028a09364220"
    url = "https://github.com/JuliaBinaryWrappers/spglib_jll.jl/releases/download/spglib-v2.5.0+0/spglib.v2.5.0.armv6l-linux-musleabihf.tar.gz"
[[spglib]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "a569b82ad8206cf69cf48d1da3ced466b603733a"
libc = "glibc"
os = "linux"

    [[spglib.download]]
    sha256 = "2c05be804d98a2f339e5e1431026981bfaa608c6390d2aa3bff72cf4d011a2c3"
    url = "https://github.com/JuliaBinaryWrappers/spglib_jll.jl/releases/download/spglib-v2.5.0+0/spglib.v2.5.0.armv7l-linux-gnueabihf.tar.gz"
[[spglib]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "73e6f4eba1efd93ab395701d395d2a937e8e618c"
libc = "musl"
os = "linux"

    [[spglib.download]]
    sha256 = "e2b111897d1e55ba70f4de6374cd1c1ae5c221dd6c700517382b0ca509702163"
    url = "https://github.com/JuliaBinaryWrappers/spglib_jll.jl/releases/download/spglib-v2.5.0+0/spglib.v2.5.0.armv7l-linux-musleabihf.tar.gz"
[[spglib]]
arch = "i686"
git-tree-sha1 = "6b9ef24fa9df11bf3e36cb6582fc015f5b3effc2"
libc = "glibc"
os = "linux"

    [[spglib.download]]
    sha256 = "68aaf9a2782ed0beffba077d9186c838224608e72f57231a148bff3ffbae5ac5"
    url = "https://github.com/JuliaBinaryWrappers/spglib_jll.jl/releases/download/spglib-v2.5.0+0/spglib.v2.5.0.i686-linux-gnu.tar.gz"
[[spglib]]
arch = "i686"
git-tree-sha1 = "93bc991314d13ca1348bd760645d2e35d83833ee"
libc = "musl"
os = "linux"

    [[spglib.download]]
    sha256 = "09eca58cf54c0891281e157d56610c2c5d3836407a967e68abea6c781bb474ab"
    url = "https://github.com/JuliaBinaryWrappers/spglib_jll.jl/releases/download/spglib-v2.5.0+0/spglib.v2.5.0.i686-linux-musl.tar.gz"
[[spglib]]
arch = "i686"
git-tree-sha1 = "95c24b8416c27d0bd8a2530e42607b8e07e867a0"
os = "windows"

    [[spglib.download]]
    sha256 = "2e285ce03a9cc96962c9420a8dfebe3932f11a99d5f07fd56c28a3c040f56325"
    url = "https://github.com/JuliaBinaryWrappers/spglib_jll.jl/releases/download/spglib-v2.5.0+0/spglib.v2.5.0.i686-w64-mingw32.tar.gz"
[[spglib]]
arch = "powerpc64le"
git-tree-sha1 = "82e5ecfeeb5fdde1f4a26491518c387ecb34c629"
libc = "glibc"
os = "linux"

    [[spglib.download]]
    sha256 = "48d8fb9007e7c2fe4390ccfe36706d6c21085a1bf186a33c1601fb4bbe0bd461"
    url = "https://github.com/JuliaBinaryWrappers/spglib_jll.jl/releases/download/spglib-v2.5.0+0/spglib.v2.5.0.powerpc64le-linux-gnu.tar.gz"
[[spglib]]
arch = "riscv64"
git-tree-sha1 = "13b659b0c7225c4d9739f93268466690faa1cf82"
libc = "glibc"
os = "linux"

    [[spglib.download]]
    sha256 = "f5b67f080d264cc411bbbc2ff6f5bf396ce74c0d317cca87aa004efcc5c793be"
    url = "https://github.com/JuliaBinaryWrappers/spglib_jll.jl/releases/download/spglib-v2.5.0+0/spglib.v2.5.0.riscv64-linux-gnu.tar.gz"
[[spglib]]
arch = "x86_64"
git-tree-sha1 = "716f9158e0e9f90834c22da3e9c15f4b132d9aaa"
os = "macos"

    [[spglib.download]]
    sha256 = "9066e9bde72c6ddc78a52f2e29fdd3e4e881a1bc8cea38eeedb8e5a569f43f0f"
    url = "https://github.com/JuliaBinaryWrappers/spglib_jll.jl/releases/download/spglib-v2.5.0+0/spglib.v2.5.0.x86_64-apple-darwin.tar.gz"
[[spglib]]
arch = "x86_64"
git-tree-sha1 = "9506d356ccb97b44fe06083af71ed4e1e0dfbbd1"
libc = "glibc"
os = "linux"

    [[spglib.download]]
    sha256 = "6cf36358bbb80941f9dc23b42fd951e04b0d6f8293638fd0070d681156b42446"
    url = "https://github.com/JuliaBinaryWrappers/spglib_jll.jl/releases/download/spglib-v2.5.0+0/spglib.v2.5.0.x86_64-linux-gnu.tar.gz"
[[spglib]]
arch = "x86_64"
git-tree-sha1 = "cee2671bfe4dea9fe77682b4bba3b4ab4103afd2"
libc = "musl"
os = "linux"

    [[spglib.download]]
    sha256 = "f5e6af53c982b9608eac0d273d604fd8250f9824d6ec9210f62e06eef6825dc0"
    url = "https://github.com/JuliaBinaryWrappers/spglib_jll.jl/releases/download/spglib-v2.5.0+0/spglib.v2.5.0.x86_64-linux-musl.tar.gz"
[[spglib]]
arch = "x86_64"
git-tree-sha1 = "59e883a55f5bc57ba26a3fdd7d9526da49553355"
os = "freebsd"

    [[spglib.download]]
    sha256 = "780215182d0bb6050c8283870d21f760fe58ed84e3499e560aa543a473b0c4e7"
    url = "https://github.com/JuliaBinaryWrappers/spglib_jll.jl/releases/download/spglib-v2.5.0+0/spglib.v2.5.0.x86_64-unknown-freebsd.tar.gz"
[[spglib]]
arch = "x86_64"
git-tree-sha1 = "25bcb5d2c6f244ac48451bc0d664cf485973734a"
os = "windows"

    [[spglib.download]]
    sha256 = "da5c71562372157223164390be6faaf403071863bd3b70639fd61ead3958921d"
    url = "https://github.com/JuliaBinaryWrappers/spglib_jll.jl/releases/download/spglib-v2.5.0+0/spglib.v2.5.0.x86_64-w64-mingw32.tar.gz"
