[[spglib]]
arch = "aarch64"
git-tree-sha1 = "1366d8dabbf6499f8c606426215fbd46ac2cb18a"
os = "macos"

    [[spglib.download]]
    sha256 = "17114aff9114b8d2e32ff213772caade1b7d7b7936b77e7996ecd05c6b0cd73b"
    url = "https://github.com/JuliaBinaryWrappers/spglib_jll.jl/releases/download/spglib-v2.7.0+0/spglib.v2.7.0.aarch64-apple-darwin.tar.gz"
[[spglib]]
arch = "aarch64"
git-tree-sha1 = "f2dfe674ba56a65994acd5ae886129ac3bb058bf"
libc = "glibc"
os = "linux"

    [[spglib.download]]
    sha256 = "fd8b056be077eba9cd11f4cfe784d22b40c1765cf725b2c66da0d3f165afe101"
    url = "https://github.com/JuliaBinaryWrappers/spglib_jll.jl/releases/download/spglib-v2.7.0+0/spglib.v2.7.0.aarch64-linux-gnu.tar.gz"
[[spglib]]
arch = "aarch64"
git-tree-sha1 = "e55be3761be1179e6c2819cfd86656ec750addd7"
libc = "musl"
os = "linux"

    [[spglib.download]]
    sha256 = "3b13e8a03bd4c21f16b9c60eb718774db16f914ec611548783150bcb546dc33b"
    url = "https://github.com/JuliaBinaryWrappers/spglib_jll.jl/releases/download/spglib-v2.7.0+0/spglib.v2.7.0.aarch64-linux-musl.tar.gz"
[[spglib]]
arch = "aarch64"
git-tree-sha1 = "149ca629298f75b6191a88a4c1c77f2cc6af68fb"
os = "freebsd"

    [[spglib.download]]
    sha256 = "78f6c843f3e7477daa82c67b9b467300e40f823901e9a10369c72b1c43848a35"
    url = "https://github.com/JuliaBinaryWrappers/spglib_jll.jl/releases/download/spglib-v2.7.0+0/spglib.v2.7.0.aarch64-unknown-freebsd.tar.gz"
[[spglib]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "43d43ae08ca28467468c4ea0e935cc1fb204ca2f"
libc = "glibc"
os = "linux"

    [[spglib.download]]
    sha256 = "c5c8d987c6d0bb21f41a46451eb456f1f82bdca2337670718f95275e599b76e4"
    url = "https://github.com/JuliaBinaryWrappers/spglib_jll.jl/releases/download/spglib-v2.7.0+0/spglib.v2.7.0.armv6l-linux-gnueabihf.tar.gz"
[[spglib]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "b9ef2538c23c234ba28942de337b49030dbc12a3"
libc = "musl"
os = "linux"

    [[spglib.download]]
    sha256 = "534c1cc847185bd51b05035bb056bd934608a4126c8ba923d24612d4b082d6bf"
    url = "https://github.com/JuliaBinaryWrappers/spglib_jll.jl/releases/download/spglib-v2.7.0+0/spglib.v2.7.0.armv6l-linux-musleabihf.tar.gz"
[[spglib]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "75540fcbd19421975fe3c9156c8b86cdf20431dc"
libc = "glibc"
os = "linux"

    [[spglib.download]]
    sha256 = "2afd338f4b99fb4bf52ffecb328bd7b284e167f4477dc50047e12a8a583e4792"
    url = "https://github.com/JuliaBinaryWrappers/spglib_jll.jl/releases/download/spglib-v2.7.0+0/spglib.v2.7.0.armv7l-linux-gnueabihf.tar.gz"
[[spglib]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "6199bbc1b35b0aa84fdce96be8a57cf62bd04d23"
libc = "musl"
os = "linux"

    [[spglib.download]]
    sha256 = "d96ad6aaf630e0344a7f4bcf32093c536081ca639c31378f0515b9c5033cc90c"
    url = "https://github.com/JuliaBinaryWrappers/spglib_jll.jl/releases/download/spglib-v2.7.0+0/spglib.v2.7.0.armv7l-linux-musleabihf.tar.gz"
[[spglib]]
arch = "i686"
git-tree-sha1 = "25c890a33b7f91011efb68c60c7a289381866676"
libc = "glibc"
os = "linux"

    [[spglib.download]]
    sha256 = "f4d3dc102ec532b2d7157e27f4828159bc17d842b93f3781ed54730c9ffa2a21"
    url = "https://github.com/JuliaBinaryWrappers/spglib_jll.jl/releases/download/spglib-v2.7.0+0/spglib.v2.7.0.i686-linux-gnu.tar.gz"
[[spglib]]
arch = "i686"
git-tree-sha1 = "f83f2bd1bebb936a8b56c6e92f3c14ea14e01c72"
libc = "musl"
os = "linux"

    [[spglib.download]]
    sha256 = "8abb43087ed9ae513c9c252e7097eade67fd27325eb5ebe1212168bd3754567f"
    url = "https://github.com/JuliaBinaryWrappers/spglib_jll.jl/releases/download/spglib-v2.7.0+0/spglib.v2.7.0.i686-linux-musl.tar.gz"
[[spglib]]
arch = "i686"
git-tree-sha1 = "01384dc5802e22a234516681f8683aff1727f5cd"
os = "windows"

    [[spglib.download]]
    sha256 = "3f528dec534b33d1e26b69ffe40102456cd53bc59c925471c7714581ef056613"
    url = "https://github.com/JuliaBinaryWrappers/spglib_jll.jl/releases/download/spglib-v2.7.0+0/spglib.v2.7.0.i686-w64-mingw32.tar.gz"
[[spglib]]
arch = "powerpc64le"
git-tree-sha1 = "f11c7d7d90c182609b7d4f4d7d2923a28b1e330e"
libc = "glibc"
os = "linux"

    [[spglib.download]]
    sha256 = "86036063a3cb9d0a6358f36ef7afc25fb25f5f6f368a4713299c9da2b6d28a5f"
    url = "https://github.com/JuliaBinaryWrappers/spglib_jll.jl/releases/download/spglib-v2.7.0+0/spglib.v2.7.0.powerpc64le-linux-gnu.tar.gz"
[[spglib]]
arch = "riscv64"
git-tree-sha1 = "e1ccbf431d410fe132cb5ebd9bde53a4e4542010"
libc = "glibc"
os = "linux"

    [[spglib.download]]
    sha256 = "468bc41c7e865727686bc9b9b935a46b244497e80a7708c72a75f13995512e65"
    url = "https://github.com/JuliaBinaryWrappers/spglib_jll.jl/releases/download/spglib-v2.7.0+0/spglib.v2.7.0.riscv64-linux-gnu.tar.gz"
[[spglib]]
arch = "x86_64"
git-tree-sha1 = "11e12afb2f5a9405bace240ee641881fcfa66d02"
os = "macos"

    [[spglib.download]]
    sha256 = "8f20698e6d92f1d798b52db0d3a373d7739de27cba57035a870aeddc88c8c1ba"
    url = "https://github.com/JuliaBinaryWrappers/spglib_jll.jl/releases/download/spglib-v2.7.0+0/spglib.v2.7.0.x86_64-apple-darwin.tar.gz"
[[spglib]]
arch = "x86_64"
git-tree-sha1 = "ceefa619e483d9651436478e4956ba71abc49fc8"
libc = "glibc"
os = "linux"

    [[spglib.download]]
    sha256 = "ba908668d97c410a6d53cf20c129a0fdcff7814dfc0177e129fefc8eec869aae"
    url = "https://github.com/JuliaBinaryWrappers/spglib_jll.jl/releases/download/spglib-v2.7.0+0/spglib.v2.7.0.x86_64-linux-gnu.tar.gz"
[[spglib]]
arch = "x86_64"
git-tree-sha1 = "23d21d42708d6744869b5f468b8b5a51b9bd0edf"
libc = "musl"
os = "linux"

    [[spglib.download]]
    sha256 = "c912db475e5c882eb3c511deaefc195dd47b3f0b0c39afc26e8b0b8744b022d8"
    url = "https://github.com/JuliaBinaryWrappers/spglib_jll.jl/releases/download/spglib-v2.7.0+0/spglib.v2.7.0.x86_64-linux-musl.tar.gz"
[[spglib]]
arch = "x86_64"
git-tree-sha1 = "4efef1c56626cbb85c5a1edc0e41364d56d725f8"
os = "freebsd"

    [[spglib.download]]
    sha256 = "bae1e0a59114de078bf231ae0ec3393a37929344465f1e94d58daada0800d771"
    url = "https://github.com/JuliaBinaryWrappers/spglib_jll.jl/releases/download/spglib-v2.7.0+0/spglib.v2.7.0.x86_64-unknown-freebsd.tar.gz"
[[spglib]]
arch = "x86_64"
git-tree-sha1 = "54306c7e7153c88707f98ade9725904f7a1b7af3"
os = "windows"

    [[spglib.download]]
    sha256 = "7963990362f7bd647ddd25682ae2c79bec5fcc159d603fca395bd52843076523"
    url = "https://github.com/JuliaBinaryWrappers/spglib_jll.jl/releases/download/spglib-v2.7.0+0/spglib.v2.7.0.x86_64-w64-mingw32.tar.gz"
